apiVersion: v1
name: luigi
version: 0.1
appVersion: 2.8.9
description: Luigi is a Python module that helps you build complex pipelines of batch
  jobs. It handles dependency resolution, workflow management, visualization etc.
  It also comes with Hadoop support built in.
home: https://luigi.readthedocs.io/en/stable/
icon: https://raw.githubusercontent.com/spotify/luigi/master/doc/luigi.png
keywords:
- luigi
- scheduler
- dependency graph
- web
- task management
- hadoop
- spark
- kubernetes job manager
maintainers:
- email: pedro@datarevenue.com
  name: pedro

sources:
- https://github.com/spotify/luigi/
- https://github.com/sammerry/luigi-docker-image/
